Fix nil command-hash
rocky/realgud-byebug pull request #2
Opened 2018-03-01 23:37 UTC by ldgonza

Registered command hash with realgud, following what the corresponding pdb module for realgud does.

Also removed the "realgud:" prefix from track-mode.el. None of the other modules seem to use the prefix and I couldn't find any side effects and everything seems to work fine, but if you can see an issue I can just discard that and resubmit.

2018-03-01 23:38 UTC, ldgonza commented
Oh and thank you for the realgud:byebug integration. I can't believe I was missing it :)

2018-03-01 23:42 UTC, rocky requested changes
The `realgud:` prefix is a namespace thing for Emacs. Commands and functions should start with `realgud`. 

That said, sure, I understand that it is more convenient and natural to run `M-x byebug` rather than `M-x realgud:byebug`.   So what is done is you make the latter be an alias for the former as such: 


```
;;;###autoload
(defalias 'byebug 'realgud:byebug)
```

2018-03-01 23:43 UTC, rocky commented
Thanks for the pull request and for the interest in realgud:byebug. If you make the small change suggested, I'll merge.

2018-03-02 00:45 UTC, rocky reviewed
Oops.

2018-03-02 00:54 UTC, ldgonza commented
Thanks for the fast response!
I think I explained it wrong: let me insist one last time; if you still don't like it I'll take the hint and just undo it:

The change doesn't alter the namespace. I still run it as realgud:byebug. The change alters an arbitrary key for an internal hash belonging to realgud. I checked other modules and they don't include a prefix, for example:

```
; gdb/track-mode.el:65
(realgud:track-set-debugger "gdb")
```
```
; perldb/track-mode.el:63
(realgud:track-set-debugger "perldb")
```

I don't think the value has any effect beside that which is given inside each module's track-mode.el. I still think it's better without the prefix for consistency.

2018-03-02 00:59 UTC, rocky approved these changes

2018-03-02 01:02 UTC, rocky commented
BTW,  you might be able to find other places for improvement by looking over the changes in realgud/realgud since the last commit I have made.

Since this project hasn't been starred by anyone other than myself, I haven't put any effort into keeping it in sync with the main core.

2018-03-02 01:02 UTC, merged

2018-03-02 01:03 UTC, rocky commented
And yes, you were correct about not altering the namespace. I make a lot of mistakes -- hence projects like this.

2018-03-02 02:08 UTC, ldgonza commented
Thanks; I appreciate the project actually, I wouldn't be able to write the integration with realgud. I'll keep an eye out if I can make other contributions.